### PR TITLE
reordering menu

### PR DESCRIPTION
**Pull request by SamGuay**
Closing #28 with this.

### CODE REVIEW

**Review by flavioazevedo — COMMENTED** [review]
Samsies, just to make sure everything is alright. In the main it appears that several pages in the toml are not going to be displayed. Is this normal?

**Comment by SamGuay** [comment]
> Samsies, just to make sure everything is alright. In the main it appears that several pages in the toml are not going to be displayed. Is this normal?

Not sure what you mean by that?

**Review by flavioazevedo — COMMENTED** [review]
image


See all the manus in red to the left? That's what I mean. I am probably wrong but I would think these would get deleted and now shown (which is not the goal).

**Comment by SamGuay** [comment]
Oh Falafla, this is a feature, not a bug. 

In sum, all the red lines will be deleted, which is what we want since these lines are created a new _Parent_ tab in the *main* menu called `FORRT`. I simply relocated these 3 menu tabs where you wanted them, see the added (green) lines to see where they go. If you are worried, you can also look at the [preview link](https://deploy-preview-34--priceless-boyd-4abbaf.netlify.app/) to make sure everything is alright.

**Review by flavioazevedo — APPROVED** [review]
Got it! thanks!

**Pull request merged**
